server:
  port: 8080
spring:
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher


mybatis-plus:
#  type-aliases-package: com.wf.**.model.pojo
#  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #??????
    map-underscore-to-camel-case: false


token:
  header: Authorization
  secret: dontNeedNoStarBuckWoo
  expireTime: 30


# ????
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# ????
user:
  password:
    # ????????
    maxRetryCount: 5
    # ?????????10???
    lockTime: 10

